name: Collect Weather Predictions (02-weather-app)

# Schedule: Daily at 00:00 UTC (09:00 KST)
on:
  schedule:
    - cron: "0 0 * * *" # Daily midnight UTC
  workflow_dispatch: # Allow manual trigger for testing

permissions:
  contents: write

jobs:
  collect-predictions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./02-weather-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: ./02-weather-app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Collect tomorrow's weather predictions
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          WEATHERAPI_KEY: ${{ secrets.WEATHERAPI_KEY }}
        run: npx tsx --tsconfig tsconfig.app.json scripts/collect-predictions.ts

      - name: Commit prediction data
        working-directory: .
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add 02-weather-app/data/predictions/*.json
          git diff --staged --quiet || git commit -m "chore: collect weather predictions for $(date -u +%Y-%m-%d)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
